# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 762e4551ce3974fa8a6ecdcf3fe49433e159ca25aeb2e0b846684d32305282d25067f9c521773e6474caab50255dacbacb5bc9c0b6709a0b7f73f09f53a581d4

test:
  secret_key_base: 84975ca0889055292f0108fc44cb2f580edd5c25461e699d24d2ab319a6d2bde988532cbe7f5545fad84ae31f4977b6051294f447394bf3bd1fb0bb7f79bb92b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
